# Generated by Django 5.0.2 on 2024-05-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrarse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario Registrado',
                'verbose_name_plural': 'Usuarios Registrados',
                'db_table': 'registrarse',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='InicioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraseña', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.registrarse')),
            ],
            options={
                'verbose_name': 'Inicio de Sesión',
                'verbose_name_plural': 'Inicios de Sesión',
                'db_table': 'inicio_sesion',
                'ordering': ['created'],
            },
        ),
    ]
