# Generated by Django 5.0.2 on 2024-06-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iniciosesion',
            options={'verbose_name': 'Inicio de Sesión', 'verbose_name_plural': 'Inicios de Sesión'},
        ),
        migrations.AlterModelOptions(
            name='registrarse',
            options={'verbose_name': 'Usuario Registrado', 'verbose_name_plural': 'Usuarios Registrados'},
        ),
        migrations.RemoveField(
            model_name='iniciosesion',
            name='created',
        ),
        migrations.RemoveField(
            model_name='iniciosesion',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='registrarse',
            name='created',
        ),
        migrations.RemoveField(
            model_name='registrarse',
            name='updated',
        ),
        migrations.AlterField(
            model_name='iniciosesion',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iniciosesion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.registrarse', to_field='correo'),
        ),
        migrations.AlterField(
            model_name='registrarse',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrarse',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrarse',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
    ]
