# Generated by Django 5.0.2 on 2024-06-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_alter_iniciosesion_options_alter_registrarse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciosesion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.registrarse'),
        ),
    ]
