# Generated by Django 5.0.2 on 2024-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0004_alter_iniciosesion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciosesion',
            name='contraseña',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registrarse',
            name='apellidos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrarse',
            name='contraseña',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registrarse',
            name='correo',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='registrarse',
            name='nombres',
            field=models.CharField(max_length=20),
        ),
    ]
