# Generated by Django 5.0.2 on 2024-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0010_alter_registrarse_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrarse',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='registrarse',
            name='nombres',
        ),
        migrations.AddField(
            model_name='registrarse',
            name='nombre_completo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrarse',
            name='nombre_usuario',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iniciosesion',
            name='contraseña',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrarse',
            name='contraseña',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrarse',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
