# Generated by Django 5.0.2 on 2024-06-24 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0011_remove_registrarse_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrarse',
            name='nombre_usuario',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de usuario debe contener solo letras y números.', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
