# Generated by Django 5.0.2 on 2024-06-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0012_alter_registrarse_nombre_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciosesion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.registrarse', to_field='nombre_usuario'),
        ),
    ]
