# Generated by Django 5.0.2 on 2024-07-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0016_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='agendada',
            field=models.BooleanField(default=False),
        ),
    ]
