# Generated by Django 5.0.2 on 2024-08-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0018_rename_agendada_cita_consultada_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='en_linea',
            field=models.BooleanField(default=False),
        ),
    ]
