# Generated by Django 5.0.2 on 2024-08-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0019_perfil_en_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
