# Generated by Django 5.0.2 on 2024-08-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0020_perfil_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='online',
        ),
    ]
