# Generated by Django 5.0.2 on 2024-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0021_remove_perfil_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
