# Generated by Django 5.0.2 on 2024-08-06 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administra', '0001_initial'),
        ('sesion', '0022_perfil_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administra.mascota'),
            preserve_default=False,
        ),
    ]
