# Generated by Django 5.0.2 on 2024-08-06 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0023_cita_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.registrarse'),
        ),
    ]
