# Generated by Django 5.0.2 on 2024-08-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0025_alter_cita_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='online',
        ),
        migrations.AddField(
            model_name='perfil',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
