# Generated by Django 5.0.2 on 2024-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0026_remove_perfil_online_perfil_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='perfil',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
