# Generated by Django 5.0.2 on 2024-08-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0028_perfil_ultima_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='ultima_actividad',
        ),
    ]
