# Generated by Django 5.0.2 on 2024-08-25 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0029_remove_perfil_ultima_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
