# Generated by Django 5.0.2 on 2024-08-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0030_perfil_ultima_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='online',
        ),
    ]
