# Generated by Django 5.0.2 on 2024-08-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0031_remove_perfil_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
