# Generated by Django 5.0.2 on 2024-08-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administra', '0002_historialmascota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialmascota',
            options={'verbose_name': 'historial mascota', 'verbose_name_plural': 'historial mascotas'},
        ),
        migrations.RenameField(
            model_name='historialmascota',
            old_name='motivo',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='historialmascota',
            name='eliminado_por',
        ),
        migrations.RemoveField(
            model_name='historialmascota',
            name='mascota',
        ),
        migrations.AddField(
            model_name='historialmascota',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmascota',
            name='foto',
            field=models.ImageField(default=1, upload_to='historial_mascotas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmascota',
            name='genero',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmascota',
            name='motivo_eliminacion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmascota',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmascota',
            name='raza',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
