# Generated by Django 5.0.2 on 2024-08-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administra', '0003_alter_historialmascota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmascota',
            name='fecha_eliminacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
