# Generated by Django 5.0.2 on 2024-08-21 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administra', '0004_alter_historialmascota_fecha_eliminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmascota',
            name='fecha_eliminacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
